### ISSUE TITLE
Defining variables multiple times throughout files?

### ISSUE THREAD

**Issue by wadehammes** [basscss/basscss-sass#3]
Just wondering why we are defining the same values throughout multiple files here? I understand it is nice to see which variables are used from a high-level per file, but maybe have the _defaults.scss includes ALL variables and then have the per-file variable list commented out by default? Just a suggestion.

I'd like to use this and just update a single variable file (for colors especially) instead of going through and removing/commenting them for each separate file I use.

**Comment by jxnblk** [comment]
This is a side effect of the [`css-scss`](https://github.com/jxnblk/css-scss) module, which converts spec-compliant CSS to Sass syntax.

Since the variables are defined with the `!default` flag, you shouldn't have to remove them from the source. Instead you should import your own variables file before any of the Basscss partials. If that's not working, please let me know.

**Comment by wadehammes** [comment]
Awesome, will let you know!
